/*
 * Cloud Functions
 * Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.
 *
 * The version of the OpenAPI document: 2.87.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AuthorizedPartiesByFunctionDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AuthorizedPartiesResponse
 */
public class AuthorizedPartiesResponseTest {
    private final AuthorizedPartiesResponse model = new AuthorizedPartiesResponse();

    /**
     * Model tests for AuthorizedPartiesResponse
     */
    @Test
    public void testAuthorizedPartiesResponse() {
        // TODO: test AuthorizedPartiesResponse
    }

    /**
     * Test the property 'function'
     */
    @Test
    public void functionTest() {
        // TODO: test function
    }

}
