/*
 * Cloud Functions
 * Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.
 *
 * The version of the OpenAPI document: 2.87.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Cluster;
import com.konfigthis.client.model.Gpu;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ClusterGroup
 */
public class ClusterGroupTest {
    private final ClusterGroup model = new ClusterGroup();

    /**
     * Model tests for ClusterGroup
     */
    @Test
    public void testClusterGroup() {
        // TODO: test ClusterGroup
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'ncaId'
     */
    @Test
    public void ncaIdTest() {
        // TODO: test ncaId
    }

    /**
     * Test the property 'authorizedNcaIds'
     */
    @Test
    public void authorizedNcaIdsTest() {
        // TODO: test authorizedNcaIds
    }

    /**
     * Test the property 'gpus'
     */
    @Test
    public void gpusTest() {
        // TODO: test gpus
    }

    /**
     * Test the property 'clusters'
     */
    @Test
    public void clustersTest() {
        // TODO: test clusters
    }

}
