/*
 * Cloud Functions
 * Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.
 *
 * The version of the OpenAPI document: 2.87.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DeploymentHealthDto;
import com.konfigthis.client.model.GpuSpecificationDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FunctionDeploymentDto
 */
public class FunctionDeploymentDtoTest {
    private final FunctionDeploymentDto model = new FunctionDeploymentDto();

    /**
     * Model tests for FunctionDeploymentDto
     */
    @Test
    public void testFunctionDeploymentDto() {
        // TODO: test FunctionDeploymentDto
    }

    /**
     * Test the property 'functionId'
     */
    @Test
    public void functionIdTest() {
        // TODO: test functionId
    }

    /**
     * Test the property 'functionVersionId'
     */
    @Test
    public void functionVersionIdTest() {
        // TODO: test functionVersionId
    }

    /**
     * Test the property 'ncaId'
     */
    @Test
    public void ncaIdTest() {
        // TODO: test ncaId
    }

    /**
     * Test the property 'functionStatus'
     */
    @Test
    public void functionStatusTest() {
        // TODO: test functionStatus
    }

    /**
     * Test the property 'requestQueueUrl'
     */
    @Test
    public void requestQueueUrlTest() {
        // TODO: test requestQueueUrl
    }

    /**
     * Test the property 'healthInfo'
     */
    @Test
    public void healthInfoTest() {
        // TODO: test healthInfo
    }

    /**
     * Test the property 'deploymentSpecifications'
     */
    @Test
    public void deploymentSpecificationsTest() {
        // TODO: test deploymentSpecifications
    }

}
