/*
 * Cloud Functions
 * Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.
 *
 * The version of the OpenAPI document: 2.87.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FunctionInvocationPollForResultUsingFunctionInvocationRequest202Response
 */
public class FunctionInvocationPollForResultUsingFunctionInvocationRequest202ResponseTest {
    private final FunctionInvocationPollForResultUsingFunctionInvocationRequest202Response model = new FunctionInvocationPollForResultUsingFunctionInvocationRequest202Response();

    /**
     * Model tests for FunctionInvocationPollForResultUsingFunctionInvocationRequest202Response
     */
    @Test
    public void testFunctionInvocationPollForResultUsingFunctionInvocationRequest202Response() {
        // TODO: test FunctionInvocationPollForResultUsingFunctionInvocationRequest202Response
    }

    /**
     * Test the property '_short'
     */
    @Test
    public void _shortTest() {
        // TODO: test _short
    }

    /**
     * Test the property '_char'
     */
    @Test
    public void _charTest() {
        // TODO: test _char
    }

    /**
     * Test the property '_int'
     */
    @Test
    public void _intTest() {
        // TODO: test _int
    }

    /**
     * Test the property '_long'
     */
    @Test
    public void _longTest() {
        // TODO: test _long
    }

    /**
     * Test the property '_float'
     */
    @Test
    public void _floatTest() {
        // TODO: test _float
    }

    /**
     * Test the property '_double'
     */
    @Test
    public void _doubleTest() {
        // TODO: test _double
    }

    /**
     * Test the property 'direct'
     */
    @Test
    public void directTest() {
        // TODO: test direct
    }

    /**
     * Test the property 'readOnly'
     */
    @Test
    public void readOnlyTest() {
        // TODO: test readOnly
    }

}
