/*
 * Cloud Functions
 * Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.
 *
 * The version of the OpenAPI document: 2.87.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InstanceDto
 */
public class InstanceDtoTest {
    private final InstanceDto model = new InstanceDto();

    /**
     * Model tests for InstanceDto
     */
    @Test
    public void testInstanceDto() {
        // TODO: test InstanceDto
    }

    /**
     * Test the property 'instanceId'
     */
    @Test
    public void instanceIdTest() {
        // TODO: test instanceId
    }

    /**
     * Test the property 'functionId'
     */
    @Test
    public void functionIdTest() {
        // TODO: test functionId
    }

    /**
     * Test the property 'functionVersionId'
     */
    @Test
    public void functionVersionIdTest() {
        // TODO: test functionVersionId
    }

    /**
     * Test the property 'instanceType'
     */
    @Test
    public void instanceTypeTest() {
        // TODO: test instanceType
    }

    /**
     * Test the property 'instanceStatus'
     */
    @Test
    public void instanceStatusTest() {
        // TODO: test instanceStatus
    }

    /**
     * Test the property 'sisRequestId'
     */
    @Test
    public void sisRequestIdTest() {
        // TODO: test sisRequestId
    }

    /**
     * Test the property 'ncaId'
     */
    @Test
    public void ncaIdTest() {
        // TODO: test ncaId
    }

    /**
     * Test the property 'gpu'
     */
    @Test
    public void gpuTest() {
        // TODO: test gpu
    }

    /**
     * Test the property 'backend'
     */
    @Test
    public void backendTest() {
        // TODO: test backend
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'instanceCreatedAt'
     */
    @Test
    public void instanceCreatedAtTest() {
        // TODO: test instanceCreatedAt
    }

    /**
     * Test the property 'instanceUpdatedAt'
     */
    @Test
    public void instanceUpdatedAtTest() {
        // TODO: test instanceUpdatedAt
    }

}
