/*
 * Cloud Functions
 * Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.
 *
 * The version of the OpenAPI document: 2.87.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.AssetResponse;
import com.konfigthis.client.model.CreateAssetRequest;
import com.konfigthis.client.model.CreateAssetResponse;
import com.konfigthis.client.model.ListAssetsResponse;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AssetManagementApi
 */
@Disabled
public class AssetManagementApiTest {

    private static AssetManagementApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new AssetManagementApi(apiClient);
    }

    /**
     * Create Asset
     *
     * Creates a unique id representing an asset and a pre-signed URL to upload the  asset artifact to AWS S3 bucket for the NVIDIA Cloud Account. Requires either  a bearer token or an api-key with &#39;invoke_function&#39; scope in the HTTP  Authorization header.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createAssetAndUrlTest() throws ApiException {
        String description = null;
        String contentType = null;
        CreateAssetResponse response = api.createAssetAndUrl(description, contentType)
                .execute();
        // TODO: test validations
    }

    /**
     * Delete Asset
     *
     * Deletes asset belonging to the current NVIDIA Cloud Account. Requires either  a bearer token or an api-key with &#39;invoke_function&#39; scope in the HTTP  Authorization header.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteAssetByIdTest() throws ApiException {
        UUID assetId = null;
        api.deleteAssetById(assetId)
                .execute();
        // TODO: test validations
    }

    /**
     * List Assets
     *
     * List assets owned by the current NVIDIA Cloud Account. Requires either a  bearer token or an api-key with invoke_function scope in the HTTP Authorization  header. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAssetsTest() throws ApiException {
        ListAssetsResponse response = api.listAssets()
                .execute();
        // TODO: test validations
    }

    /**
     * Show Asset Details
     *
     * Returns details for the specified asset-id belonging to the current NVIDIA  Cloud Account. Requires either a bearer token or an api-key with  &#39;invoke_function&#39; scope in the HTTP Authorization header. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void showDetailsTest() throws ApiException {
        UUID assetId = null;
        AssetResponse response = api.showDetails(assetId)
                .execute();
        // TODO: test validations
    }

}
