/*
 * Cloud Functions
 * Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.
 *
 * The version of the OpenAPI document: 2.87.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ArtifactDto;
import com.konfigthis.client.model.ContainerEnvironmentEntryDto;
import com.konfigthis.client.model.CreateFunctionRequest;
import com.konfigthis.client.model.CreateFunctionResponse;
import com.konfigthis.client.model.FunctionResponse;
import com.konfigthis.client.model.ListFunctionIdsResponse;
import com.konfigthis.client.model.ListFunctionsResponse;
import java.util.Set;
import java.net.URI;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FunctionManagementApi
 */
@Disabled
public class FunctionManagementApiTest {

    private static FunctionManagementApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new FunctionManagementApi(apiClient);
    }

    /**
     * Create Function Version
     *
     * Creates a version of the specified function within the authenticated NVIDIA  Cloud Account. Requires a bearer token with &#39;register_function&#39; scope in the  HTTP Authorization header. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createFunctionVersionTest() throws ApiException {
        String name = null;
        URI inferenceUrl = null;
        UUID functionId = null;
        URI healthUri = null;
        Integer inferencePort = null;
        String containerArgs = null;
        List<ContainerEnvironmentEntryDto> containerEnvironment = null;
        Set<ArtifactDto> models = null;
        URI containerImage = null;
        URI helmChart = null;
        String helmChartServiceName = null;
        Set<ArtifactDto> resources = null;
        String apiBodyFormat = null;
        CreateFunctionResponse response = api.createFunctionVersion(name, inferenceUrl, functionId)
                .healthUri(healthUri)
                .inferencePort(inferencePort)
                .containerArgs(containerArgs)
                .containerEnvironment(containerEnvironment)
                .models(models)
                .containerImage(containerImage)
                .helmChart(helmChart)
                .helmChartServiceName(helmChartServiceName)
                .resources(resources)
                .apiBodyFormat(apiBodyFormat)
                .execute();
        // TODO: test validations
    }

    /**
     * Delete Function
     *
     * Deletes the specified function version in the authenticated NVIDIA Cloud  Account. Requires a bearer token with &#39;delete_function&#39; scope in the HTTP  Authorization header. If the function version is public, then Account Admin  cannot delete the function. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteFunctionVersionTest() throws ApiException {
        UUID functionId = null;
        UUID functionVersionId = null;
        api.deleteFunctionVersion(functionId, functionVersionId)
                .execute();
        // TODO: test validations
    }

    /**
     * Get Function Version Details
     *
     * Retrieves detailed information of the specified function version in the  authenticated NVIDIA Cloud Account. Requires either a bearer token or an  api-key with &#39;list_functions&#39; or &#39;list_functions_details&#39; scopes in the HTTP  Authorization header. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getVersionDetailsTest() throws ApiException {
        UUID functionId = null;
        UUID functionVersionId = null;
        FunctionResponse response = api.getVersionDetails(functionId, functionVersionId)
                .execute();
        // TODO: test validations
    }

    /**
     * List Function Ids
     *
     * Lists ids of all the functions in the authenticated NVIDIA Cloud Account.  Requires either a bearer token or an api-key with &#39;list_functions&#39; or  &#39;list_functions_details&#39; scopes in the HTTP Authorization header. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listFunctionIdsTest() throws ApiException {
        Set<String> visibility = null;
        ListFunctionIdsResponse response = api.listFunctionIds()
                .visibility(visibility)
                .execute();
        // TODO: test validations
    }

    /**
     * List Function Versions
     *
     * Lists details of all the versions of the specified function in the authenticated  NVIDIA Cloud Account. Requires either a bearer token or an api-key with  &#39;list_functions&#39; or &#39;list_functions_details&#39; scopes in the HTTP Authorization  header. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listFunctionVersionsTest() throws ApiException {
        UUID functionId = null;
        ListFunctionsResponse response = api.listFunctionVersions(functionId)
                .execute();
        // TODO: test validations
    }

    /**
     * List Functions
     *
     * Lists all the functions associated with the authenticated NVIDIA Cloud Account.  Requires either a bearer token or an api-key with &#39;list_functions&#39; or  &#39;list_functions_details&#39; scopes in the HTTP Authorization header.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listFunctionsTest() throws ApiException {
        Set<String> visibility = null;
        ListFunctionsResponse response = api.listFunctions()
                .visibility(visibility)
                .execute();
        // TODO: test validations
    }

    /**
     * Create Function
     *
     * Creates a new function within the authenticated NVIDIA Cloud Account. Requires a  bearer token with &#39;register_function&#39; scope in the HTTP Authorization header. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void registerNewFunctionTest() throws ApiException {
        String name = null;
        URI inferenceUrl = null;
        URI healthUri = null;
        Integer inferencePort = null;
        String containerArgs = null;
        List<ContainerEnvironmentEntryDto> containerEnvironment = null;
        Set<ArtifactDto> models = null;
        URI containerImage = null;
        URI helmChart = null;
        String helmChartServiceName = null;
        Set<ArtifactDto> resources = null;
        String apiBodyFormat = null;
        CreateFunctionResponse response = api.registerNewFunction(name, inferenceUrl)
                .healthUri(healthUri)
                .inferencePort(inferencePort)
                .containerArgs(containerArgs)
                .containerEnvironment(containerEnvironment)
                .models(models)
                .containerImage(containerImage)
                .helmChart(helmChart)
                .helmChartServiceName(helmChartServiceName)
                .resources(resources)
                .apiBodyFormat(apiBodyFormat)
                .execute();
        // TODO: test validations
    }

}
