/*
 * Cloud Functions
 * Since its founding in 1993, NVIDIA (NASDAQ: NVDA) has been a pioneer in accelerated computing. The company's invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics, ignited the era of modern AI and is fueling the creation of the metaverse. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.
 *
 * The version of the OpenAPI document: 2.87.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.GetPositionInQueueResponse;
import com.konfigthis.client.model.GetQueuesResponse;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for QueueDetailsApi
 */
@Disabled
public class QueueDetailsApiTest {

    private static QueueDetailsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new QueueDetailsApi(apiClient);
    }

    /**
     * Queue Details
     *
     * Provides details of all the queues associated with the specified function.  If a function has multiple versions and they are all deployed, then the  response includes details of all the queues. If the specified function  is public, then Account Admin cannot perform this operation. Requires a bearer token or an api-key with &#39;queue_details&#39; scope in the HTTP  Authorization header. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void functionQueuesDetailsTest() throws ApiException {
        UUID functionId = null;
        GetQueuesResponse response = api.functionQueuesDetails(functionId)
                .execute();
        // TODO: test validations
    }

    /**
     * Queue Details
     *
     * Provides details of all the queues associated with the specified function.  If a function has multiple versions and they are all deployed, then the  response includes details of all the queues. If the specified function  is public, then Account Admin cannot perform this operation. Requires a bearer token or an api-key with &#39;queue_details&#39; scope in the HTTP  Authorization header. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllQueuesDetailsTest() throws ApiException {
        UUID functionId = null;
        UUID versionId = null;
        GetQueuesResponse response = api.getAllQueuesDetails(functionId, versionId)
                .execute();
        // TODO: test validations
    }

    /**
     * Queue Position
     *
     * Using the specified function invocation request id, returns the estimated  position of the corresponding message up to 1000 in the queue. Requires a bearer token or an api-key with &#39;queue_details&#39; scope in the HTTP  Authorization header. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getQueuePositionByRequestIdTest() throws ApiException {
        UUID requestId = null;
        GetPositionInQueueResponse response = api.getQueuePositionByRequestId(requestId)
                .execute();
        // TODO: test validations
    }

}
